[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
included_files = ["netlify/functions/data/**"]

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/express/:splat"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200